### ISSUE TITLE
android 9 上显示不了

### ISSUE THREAD

**Issue by mcxinyu** [xiaofei-dev/RoundWidget#1]
MI CC 9e android9 上使用圆角会看不到内容

可以到 https://testit.miui.com/remote 云测上真机调试试试

**Comment by xiaofeidev** [comment]
我用你给的云测试机看了看没问题啊？

**Comment by xiaofeidev** [comment]
> MI CC 9e android9 上使用圆角会看不到内容
> 
> 可以到 https://testit.miui.com/remote 云测上真机调试试试

我又发了个新版本（1.1.0），改善了下内部实现，你再试试还有没有问题

**Comment by mcxinyu** [comment]
感谢，工程比较急，我暂时用其他方式实现了

**Comment by xiaofeidev** [comment]
> 感谢，工程比较急，我暂时用其他方式实现了

好的，我前段时间也比较忙没过来看，加了一层缓冲试了试应该不会有黑色背景的问题了
